import json
from pathlib import Path


def generate_cosim_runner(config: dict, output_path: Path) -> None:
    scenario_id = config["scenario_id"]
    profile = config.get("profile", "paper")
    code = f"""# Auto-generated by MARTIAN-like code generator
import argparse
import json
import os
import sys
from pathlib import Path

BASE = Path(__file__).resolve().parents[3] / "0422" / "simulatoragent"
sys.path.insert(0, str(BASE))

from scenarios import get_scenario
from fmu_sim import CoSimRunner


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--params-json", required=True)
    ap.add_argument("--n-trials", type=int, default=3)
    args = ap.parse_args()

    os.environ["SIM_PROTOCOL_PROFILE"] = "{profile}"
    scenario = get_scenario("{scenario_id}")
    runner = CoSimRunner(scenario)

    params = json.loads(args.params_json)
    result = runner.run_n_trials(override_params=params, n=args.n_trials)
    print(json.dumps(result, ensure_ascii=False))


if __name__ == "__main__":
    main()
"""
    output_path.write_text(code, encoding="utf-8")


def load_config(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))
